cluster_shape = ["circle", "circle-open", "circle-dot", "circle-open-dot",
                 "square", "square-open", "square-dot", "square-open-dot",
                 "diamond", "diamond-open", "diamond-dot", "diamond-open-dot",
                 "cross", "cross-open", "cross-dot", "cross-open-dot",
                 "x", "x-open", "x-dot", "x-open-dot",
                 "triangle-up", "triangle-up-open", "triangle-up-dot", "triangle-up-open-dot",
                 "triangle-down", "triangle-down-open", "triangle-down-dot", "triangle-down-open-dot",
                 "triangle-left", "triangle-left-open", "triangle-left-dot", "triangle-left-open-dot",
                 "triangle-right", "triangle-right-open", "triangle-right-dot", "triangle-right-open-dot",
                 "triangle-ne", "triangle-ne-open", "triangle-ne-dot", "triangle-ne-open-dot",
                 "triangle-se", "triangle-se-open", "triangle-se-dot", "triangle-se-open-dot",
                 "triangle-sw", "triangle-sw-open", "triangle-sw-dot", "triangle-sw-open-dot",
                 "triangle-nw", "triangle-nw-open", "triangle-nw-dot", "triangle-nw-open-dot",
                 "pentagon", "pentagon-open", "pentagon-dot", "pentagon-open-dot",
                 "hexagon", "hexagon-open", "hexagon-dot", "hexagon-open-dot",
                 "hexagon2", "hexagon2-open", "hexagon2-dot", "hexagon2-open-dot",
                 "octagon", "octagon-open", "octagon-dot", "octagon-open-dot",
                 "star", "star-open", "star-dot", "star-open-dot",
                 "hexagram", "hexagram-open", "hexagram-dot", "hexagram-open-dot",
                 "star-triangle-up", "star-triangle-up-open", "star-triangle-up-dot", "star-triangle-up-open-dot",
                 "star-triangle-down", "star-triangle-down-open", "star-triangle-down-dot",
                 "star-triangle-down-open-dot",
                 "star-square", "star-square-open", "star-square-dot", "star-square-open-dot",
                 "star-diamond", "star-diamond-open", "star-diamond-dot", "star-diamond-open-dot",
                 "diamond-tall", "diamond-tall-open", "diamond-tall-dot", "diamond-tall-open-dot",
                 "diamond-wide", "diamond-wide-open", "diamond-wide-dot", "diamond-wide-open-dot",
                 "hourglass", "hourglass-open",
                 "bowtie", "bowtie-open",
                 "circle-cross", "circle-cross-open",
                 "circle-x", "circle-x-open",
                 "square-cross", "square-cross-open",
                 "square-x", "square-x-open",
                 "diamond-cross", "diamond-cross-open",
                 "diamond-x", "diamond-x-open",
                 "cross-thin", "cross-thin-open",
                 "x-thin", "x-thin-open",
                 "asterisk", "asterisk-open",
                 "hash", "hash-open", "hash-dot", "hash-open-dot",
                 "y-up", "y-up-open",
                 "y-down", "y-down-open",
                 "y-left", "y-left-open",
                 "y-right", "y-right-open",
                 "line-ew", "line-ew-open",
                 "line-ns", "line-ns-open",
                 "line-ne", "line-ne-open",
                 "line-nw", "line-nw-open",
                 "arrow-up", "arrow-up-open",
                 "arrow-down", "arrow-down-open",
                 "arrow-left", "arrow-left-open",
                 "arrow-right", "arrow-right-open",
                 "arrow-bar-up", "arrow-bar-up-open",
                 "arrow-bar-down", "arrow-bar-down-open",
                 "arrow-bar-left", "arrow-bar-left-open",
                 "arrow-bar-right", "arrow-bar-right-open"
                 ]
cluster_shape2 = ["circle", "square", "diamond", "cross", "x",
                  "triangle-up", "triangle-down", "triangle-left", "triangle-right", "triangle-ne",
                  "triangle-se", "triangle-sw", "triangle-nw", "pentagon", "hexagon",
                  "hexagon2", "octagon", "star", "hexagram", "star-triangle-up",
                  "star-triangle-down", "star-square", "star-diamond", "diamond-tall", "diamond-wide",
                  "hourglass", "bowtie", "circle-cross", "circle-x", "square-cross",
                  "square-x", "diamond-cross", "diamond-x", "cross-thin", "x-thin",
                  "asterisk", "hash", "y-up", "y-down", "y-left",
                  "y-right", "line-ew", "line-ns", "line-ne", "line-nw",
                  "arrow-up", "arrow-down", "arrow-left", "arrow-right", "arrow-bar-up",
                  "arrow-bar-down", "arrow-bar-left", "arrow-bar-right", "circle-open", "square-open",
                  "diamond-open", "cross-open", "x-open", "triangle-up-open", "triangle-down-open",
                  "triangle-left-open", "triangle-right-open", "triangle-ne-open", "triangle-se-open",
                  "triangle-sw-open",
                  "triangle-nw-open", "pentagon-open", "hexagon-open", "hexagon2-open", "octagon-open",
                  "star-open", "hexagram-open", "star-triangle-up-open", "star-triangle-down-open", "star-square-open",
                  "star-diamond-open", "diamond-tall-open", "diamond-wide-open", "hourglass-open", "bowtie-open",
                  "circle-cross-open", "circle-x-open", "square-cross-open", "square-x-open", "diamond-cross-open",
                  "diamond-x-open", "cross-thin-open", "x-thin-open", "asterisk-open", "hash-open",
                  "y-up-open", "y-down-open", "y-left-open", "y-right-open", "line-ew-open",
                  "line-ns-open", "line-ne-open", "line-nw-open", "arrow-up-open", "arrow-down-open",
                  "arrow-left-open", "arrow-right-open", "arrow-bar-up-open", "arrow-bar-down-open",
                  "arrow-bar-left-open",
                  "arrow-bar-right-open", "circle-dot", "square-dot", "diamond-dot", "cross-dot",
                  "x-dot", "triangle-up-dot", "triangle-down-dot", "triangle-left-dot", "triangle-right-dot",
                  "triangle-ne-dot", "triangle-se-dot", "triangle-sw-dot", "triangle-nw-dot", "pentagon-dot",
                  "hexagon-dot", "hexagon2-dot", "octagon-dot", "star-dot", "hexagram-dot",
                  "star-triangle-up-dot", "star-triangle-down-dot", "star-square-dot", "star-diamond-dot",
                  "diamond-tall-dot",
                  "diamond-wide-dot", "hash-dot", "circle-open-dot", "square-open-dot", "diamond-open-dot",
                  "cross-open-dot", "x-open-dot", "triangle-up-open-dot", "triangle-down-open-dot",
                  "triangle-left-open-dot",
                  "triangle-right-open-dot", "triangle-ne-open-dot", "triangle-se-open-dot", "triangle-sw-open-dot",
                  "triangle-nw-open-dot",
                  "pentagon-open-dot", "hexagon-open-dot", "hexagon2-open-dot", "octagon-open-dot", "star-open-dot",
                  "hexagram-open-dot", "star-triangle-up-open-dot", "star-triangle-down-open-dot",
                  "star-square-open-dot", "star-diamond-open-dot",
                  "diamond-tall-open-dot", "diamond-wide-open-dot", "hash-open-dot"]
